# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8UGx1sJ4cX9G4aY2ntS2QZGzUqQ4j1T
"""

def most_frequent(input_string):
    # Create an empty dictionary to store letter frequencies
    letter_count = {}

    # Remove spaces and convert the string to lowercase for case-insensitive counting
    input_string = input_string.replace(" ", "").lower()

    # Count the frequency of each letter and store it in the dictionary
    for letter in input_string:
        if letter.isalpha():
            if letter in letter_count:
                letter_count[letter] += 1
            else:
                letter_count[letter] = 1

    # Sort the dictionary by frequency in decreasing order
    sorted_letter_count = dict(sorted(letter_count.items(), key=lambda item: item[1], reverse=True))

    # Print the letters and their frequencies
    for letter, frequency in sorted_letter_count.items():
        print(f"{letter} = {frequency:02d}", end=" ")

# Input from the user
input_string = input("Please enter a string: ")

# Call the function and display the result
most_frequent(input_string)