# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8UGx1sJ4cX9G4aY2ntS2QZGzUqQ4j1T
"""

# Dictionary to map common file extensions to their names
extension_names = {
    "py": "Python",
    "txt": "Text",
    # Add more extensions and names as needed
}

# Accept the filename from the user
filename = input("Input the Filename: ")

# Split the filename by the dot to get the extension
parts = filename.split(".")
if len(parts) > 1:
    extension = parts[-1]
    if extension in extension_names:
        print(f"The extension of the file is: '{extension_names[extension]}'")
    else:
        print(f"The extension of the file is: '{extension}'")
else:
    print("No extension found in the filename.")