# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8UGx1sJ4cX9G4aY2ntS2QZGzUqQ4j1T
"""

import math

# Accept the radius from the user
radius = float(input("Input the radius of the circle: "))

# Calculate the area of the circle
area = math.pi * (radius ** 2)

# Display the result
print(f"The area of the circle with radius {radius} is: {area}")