# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8UGx1sJ4cX9G4aY2ntS2QZGzUqQ4j1T
"""

# Function to print all positive numbers in a list
def print_positive_numbers(input_list):
    positive_numbers = [num for num in input_list if num > 0]

    # Check if there are any positive numbers
    if positive_numbers:
        print("Output:", ", ".join(map(str, positive_numbers)))
    else:
        print("No positive numbers found in the list.")

# Input list from the user
list1 = [12, -7, 5, 64, -14]
print("Input:", list1)
print_positive_numbers(list1)

list2 = [12, 14, -95, 3]
print("\nInput:", list2)
print_positive_numbers(list2)