# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8UGx1sJ4cX9G4aY2ntS2QZGzUqQ4j1T
"""

class Student:
    def __init__(self, rollno, name, age, marks):
        self.rollno = rollno
        self.name = name
        self.age = age
        self.marks = marks

    def display_student(self):
        print(f"Roll No: {self.rollno}")
        print(f"Name: {self.name}")
        print(f"Age: {self.age}")
        print(f"Marks: {self.marks}")
        print("-----------")

def add_student():
    rollno = input("Enter Roll No: ")
    name = input("Enter Name: ")
    age = input("Enter Age: ")
    marks = input("Enter Marks: ")

    student = Student(rollno, name, age, marks)
    students.append(student)
    print(f"Student {name} added successfully!")

def view_student(rollno):
    for student in students:
        if student.rollno == rollno:
            student.display_student()
            return
    print(f"Student with Roll No {rollno} not found.")

def display_all_students():
    for student in students:
        student.display_student()

students = []

while True:
    print("\nSchool Administration Program")
    print("1. Add Student")
    print("2. View Student")
    print("3. Display All Students")
    print("4. Exit")

    choice = input("Enter your choice (1/2/3/4): ")

    if choice == '1':
        add_student()
    elif choice == '2':
        rollno = input("Enter Roll No of the student to view: ")
        view_student(rollno)
    elif choice == '3':
        display_all_students()
    elif choice == '4':
        print("Exiting School Administration Program. Goodbye!")
        break
    else:
        print("Invalid choice. Please enter a valid option.")