# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14RAy68UNe63rvNRd-XVt1AasK_QZmTEb
"""

# Input list
list1 = [12, -7, 5, 64, -14]
list2 = [12,14,-95,3]
# Filter positive numbers
positive_numbers = [num for num in list1 if num > 0]
positive_numbers1 = [num for num in list2 if num > 0]

# Print the positive numbers
print("Input:", list1,list2)
print("Output:", positive_numbers,positive_numbers1)