# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8UGx1sJ4cX9G4aY2ntS2QZGzUqQ4j1T
"""

import sqlite3

# Connect to the database or create it if it doesn't exist
conn = sqlite3.connect("scraped_data.db")
cursor = conn.cursor()

# Create a table to store the data
cursor.execute("""
CREATE TABLE IF NOT EXISTS scraped_info (
    title TEXT,
    link TEXT
)
""")

# Commit and close the connection
conn.commit()
conn.close()